name: Bench

# TODO: fix - sometimes getting this error
# /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-jit-c)

on: [push]

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    environment: meta-tracing-environment
    container:  
      image: iamkimchi/pypy-trace:latest
    steps:
    - uses: actions/checkout@v3
    - name: Download PyPy
      run: make get-pypy
    - name: lfs install
      run: git lfs install
    - name: lfs pull
      run: git lfs pull
    - name: fs test
      run: |
        file ./bin/0.4.0/0.4.0_990f4184c71810fb7aaa3478b0e403a953f4324b_main-c
        ./bin/0.4.0/0.4.0_990f4184c71810fb7aaa3478b0e403a953f4324b_main-c ./programs/loops.ki
    - name: Bench 0.0.4 [loops.ki]
      run: |
        hyperfine -m 100 -M 100 './bin/0.4.0/0.4.0_990f4184c71810fb7aaa3478b0e403a953f4324b_main-c ./programs/loops.ki' \
         'bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-c ./programs/loops.ki self-like'
    - name: Bench 0.0.4 [loops_recursive.ki]
      run: |
        hyperfine './bin/0.4.0/0.4.0_990f4184c71810fb7aaa3478b0e403a953f4324b_main-c ./programs/loops.ki ./programs/loops_recursive.ki' \
         'bin/0.4.0/0.4.0_0ef9af68f13bc45c233617e2d2954df62ebfdd78_main-c ./programs/loops_recursive.ki self-like'
